name: build-use-cases
on:
  push:
    paths:
      - 'projects/ts-morph-structures/*'
      - '.github/workflows/**'
      - 'projects/ts-morph-structures/stage_2_snapshot/snapshot/source/**'
      - 'projects/ts-morph-structures/use-cases/**'
jobs:
  build-use-cases:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './projects/ts-morph-structures'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run use-cases
        timeout-minutes: 5
      - run: npm run is-repo-clean
